# Generated by Django 6.0.3 on 2026-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='suggested_bloom_level',
            field=models.CharField(choices=[('L1', 'Knowledge'), ('L2', 'Comprehension'), ('L3', 'Application'), ('L4', 'Analysis'), ('L5', 'Synthesis'), ('L6', 'Evaluation')], default='L1', max_length=2),
        ),
        migrations.AddField(
            model_name='topic',
            name='weightage',
            field=models.PositiveSmallIntegerField(default=10, help_text='Weightage in marks (relative)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for AI context'),
        ),
    ]
