# Generated by Django 6.0.3 on 2026-03-14 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_topic_suggested_bloom_level_topic_weightage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Course code must be 3 capital letters followed by 3 digits (e.g., CST203)', regex='^[A-Z]{3}[0-9]{3}$')]),
        ),
    ]
