# Generated by Django 6.0.3 on 2026-03-14 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid course code format. Example: CST203', regex='^[A-Z]{3}[0-9]{3}$')]),
        ),
    ]
