# Generated by Django 6.0.3 on 2026-03-12 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaperquestion',
            name='slot',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
